# Generated by Django 6.0.2 on 2026-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
