# Generated by Django 6.0.2 on 2026-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
